CREATE DATABASE Exercise1;
CREATE TABLE EMP_1(EMP_NUM CHAR (3), EMP_Lname VARCHAR(15), EMP_FNAME VARCHAR(15), EMP_INITIAL CHAR(1), EMP_HIREDATE DATE, JOB_CODE CHAR(3));
INSERT INTO EMP_1 (EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('222', 'Ferrer', 'Zelpha Grace', 'F', '1978-11-07', 456);
INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('111', 'Roldan', 'Xienina', 'F', '2003-03-09', 123);
INSERT INTO EMP_1 (EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('333', 'Roldan', 'Juanito', 'V', '1978-11-03', 502);
SELECT * FROM EMP_1 WHERE JOB_CODE = '502';
SELECT * FROM EMP_1;
